# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/prepare_input.smk"
include: "rules/protein_search.smk"
include: "rules/reporting.smk"


# target rule
# -----------------------------------------------------
rule all:
    input:
        "results/email/email.log",
        "results/clean_up/clean_up.log",
