# global options
samplesheet: "test/input/config/samplesheet.tsv"
database: "test/input/database/database.fasta"
workflow: "from_samplesheet"
output: "test/output/"

# module options
decoypyrat:
  cleavage_sites: "KR"
  decoy_prefix: "rev"

fragpipe:
  path: "/home/michael/Downloads/fragpipe/bin"

msstats:
  logTrans: 2
  normalization: "equalizeMedians"
  featureSubset: "all"
  summaryMethod: "TMP"
  MBimpute: True
  use_log_file: False

report:
  html: True
  pdf: True

email:
  send: False
  port: 0
  smtp_server: "smtp.example.com"
  smtp_user: "user"
  smtp_pw: "password"
  from: "sender@email.com"
  to: ["receiver@email.com"]
  subject: "Results MS proteomics pipeline"
