# global options
samplesheet: 'test/input/config/samplesheet.tsv'
database: 'test/input/database/database.fasta'
workflow: 'from_samplesheet'
output: 'test/output/'

# module options
fragpipe:
  path: '/home/michael/Downloads/fragpipe/bin'

msstats:
  logTrans: 2
  normalization: 'equalizeMedians'
  featureSubset: 'all'
  summaryMethod: 'TMP'
  MBimpute: True
  use_log_file: False

report:
  html: True
