name: Deploy Apptainer

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy-apptainer:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: MPUSP/mpusp-github-actions/.github/workflows/deploy-apptainer.yml@main
